Repository price-offer/offer-fe, pull requests merged in 2022-08, with the labels that each got.

#1 초기 환경 설정
  .eslintrc.json
  .github/ISSUE_TEMPLATE/offer_issue_template.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .husky/pre-commit
  .lintstagedrc.js
  .prettierrc
  .storybook/main.js
  .storybook/preview.js
  README.md
  next-env.d.ts
  next.config.js
  package.json
  src/pages/_app.tsx
  src/pages/index.tsx
  tsconfig.json
  tsconfig.path.json
  yarn.lock
Labels: config, review

#11 chore: 오타 수정 및 불필요한 lint, 주석 제거
  .eslintrc.json
  src/pages/index.tsx
  src/themes/colors.ts
Labels: chore

#13 config: storybook theme 설정
  .storybook/preview.js
Labels: config

#15 chore: border theme 속성명 변경
  src/themes/border.ts
Labels: chore

#17 config: Next image storybook 추가 설정, Avatar icon alias 설정
  .storybook/preview.js
  package.json
  public/icons/avatar.svg
  src/constants/icons.ts
Labels: config
