Repository price-offer/offer-fe, pull requests merged in 2023-11, with the labels that each got.

#129 feat: 쪽지 페이지 마크업
  .vscode/settings.json
  package.json
  public/images/checkboard.png
  public/images/mail.png
  public/images/message.svg
  src/@types/emotion.d.ts
  src/components/index.ts
  src/components/messagebox/Chatting/Chatting.stories.tsx
  src/components/messagebox/Chatting/Receive.tsx
  src/components/messagebox/Chatting/Send.tsx
  src/components/messagebox/Chatting/index.tsx
  src/components/messagebox/Chatting/styled.ts
  src/components/messagebox/Chatting/types.ts
  src/components/messagebox/ChattingRoom/ChattingRoom.stories.tsx
  src/components/messagebox/ChattingRoom/index.tsx
  src/components/messagebox/ChattingRoom/styled.ts
  src/components/messagebox/ChattingRoom/types.ts
  src/components/messagebox/MessageBoxPlaceholder/MessageBoxPlaceholder.stories.tsx
  src/components/messagebox/MessageBoxPlaceholder/index.tsx
  src/components/messagebox/MessageBoxPlaceholder/styled.ts
  src/components/messagebox/MessageBoxPlaceholder/types.ts
  src/components/messagebox/MessagePreview/MessagePreview.stories.tsx
  src/components/messagebox/MessagePreview/index.tsx
  src/components/messagebox/MessagePreview/styled.ts
  src/components/messagebox/MessagePreview/types.ts
  src/components/messagebox/ProductBubble/ProductBubble.stories.tsx
  src/components/messagebox/ProductBubble/index.tsx
  src/components/messagebox/ProductBubble/styled.ts
  src/components/messagebox/ProductBubble/types.ts
  src/components/messagebox/index.ts
  src/pages/messagebox/index.tsx
  src/styles/themes/index.ts
  src/styles/themes/mixins.ts
  src/styles/themes/theme.ts
  src/utils/format/index.ts
  yarn.lock
Labels: feat, Waiting Code Review

#145 fix: msw 마이그레이션
  package.json
  public/mockServiceWorker.js
  src/mocks/browser.ts
  src/mocks/handlers.ts
  yarn.lock
Labels: fix, In Progress Code Review

#132 feat: 헤더 / 사이드바 컴포넌트
  src/assets/images/Logo.png
  src/assets/images/logo.svg
  src/components/common/CommonModal/index.tsx
  src/components/common/Dialog/Dialog.stories.tsx
  src/components/common/Dialog/index.tsx
  src/components/common/Dialog/styled.ts
  src/components/common/Dialog/types.ts
  src/components/common/Header/Header.stories.tsx
  src/components/common/Header/SearchArea/index.tsx
  src/components/common/Header/SearchArea/styled.ts
  src/components/common/Header/SearchArea/types.ts
  src/components/common/Header/SideBar/index.tsx
  src/components/common/Header/SideBar/styled.ts
  src/components/common/Header/SideBar/types.ts
  src/components/common/Header/index.tsx
  src/components/common/Header/styled.ts
  src/components/common/Header/types.ts
  src/constants/images.ts
  src/pages/_app.tsx
Labels: feat, In Progress Code Review

#151 chore: public/image 디렉토리 정리
  public/images/category_mangoods.svg
  public/images/checkboard.png
  public/images/logo.svg
  public/images/mail.png
  public/images/pngLogo.png
  src/assets/images/Logo.png
  src/assets/images/checkboard.svg
  src/assets/images/mail.svg
  src/assets/images/message.svg
  src/components/messagebox/MessageBoxPlaceholder/MessageBoxPlaceholder.stories.tsx
  src/components/messagebox/MessagePreview/index.tsx
  src/constants/images.ts
  src/pages/messagebox/index.tsx
  yarn.lock
Labels: chore, Waiting Code Review

#157 chore: 파비콘 변경
  public/favicon.ico
Labels: chore

#158 fix: package dependencies install 시, 오류 현상 해결
  .nvmrc
  package.json
  public/mockServiceWorker.js
  yarn.lock
Labels: config, fix

#160 chore: upgrade package
  package.json
Labels: chore

#159 config: cd 환경 구축
  .github/workflows/cd.yml
  .vscode/settings.json
  build.sh
  package.json
  yarn.lock
Labels: config

#165 config: ods 버전 업그레이드
  .vscode/settings.json
  package.json
  yarn.lock
Labels: config

#152 feat: posting 페이지 컴포넌트 및 페이지 구현
  src/components/index.ts
  src/components/post/PostForm/PostingForm.stories.tsx
  src/components/post/PostForm/index.tsx
  src/components/post/PostForm/styled.ts
  src/components/post/PostForm/types.ts
  src/components/post/index.ts
  src/pages/post/index.tsx
Labels: feat, In Progress Code Review

#164 feat: axios 구조화 및 타입 정의
  src/apis/sample/api.ts
  src/utils/http/index.ts
Labels: feat, In Progress Code Review
