Repository price-offer/offer-fe, pull requests merged in 2023-10, with the labels that each got.

#114 fix: 스토리북 폰트 깨지는 이슈 수정
  .vscode/settings.json
  src/styles/global.tsx
Labels: fix, Finish Code Review

#107 feat: 구매자 선택 모달 구현
  src/components/mypage/SelectBuyerModal/SelectBuyerModal.stories.tsx
  src/components/mypage/SelectBuyerModal/index.tsx
  src/components/mypage/SelectBuyerModal/styled.ts
  src/components/mypage/SelectBuyerModal/types.ts
  src/components/mypage/index.ts
Labels: feat, Finish Code Review

#118 feat: Confirm Modal 사용 방식 수정
  .storybook/config/nextImage.js
  .storybook/main.js
  .storybook/preview.js
  src/components/common/CommonModal/CommonModal.stories.tsx
  src/components/common/CommonModal/index.tsx
  src/components/common/CommonModal/styled.ts
  src/components/common/CommonModal/types.ts
  src/components/common/ConfirmModal/ConfirmModal.stories.tsx
  src/components/common/ConfirmModal/index.tsx
  src/components/common/ConfirmModal/types.ts
  src/components/common/index.ts
Labels: feat, Finish Code Review

#121 config: offer-ui/react package 업그레이드
  package.json
  src/hooks/useResponsive.test.ts
  yarn.lock
Labels: config

#106 feat: 가격 제안 모달 구현
  src/components/product/PriceOfferModal/PriceOfferModal.stories.tsx
  src/components/product/PriceOfferModal/index.tsx
  src/components/product/PriceOfferModal/styled.ts
  src/components/product/PriceOfferModal/types.ts
  src/components/product/index.ts
  src/constants/app.ts
  src/types/service.ts
Labels: feat, Finish Code Review

#108 Feat: 거래후기, 거래후기 확인 모달 작업
  src/components/common/AlertModal/AlertModal.stories.tsx
  src/components/common/AlertModal/index.tsx
  src/components/common/AlertModal/styled.ts
  src/components/common/AlertModal/types.ts
  src/components/mypage/ReviewModal/Read/index.tsx
  src/components/mypage/ReviewModal/Read/types.ts
  src/components/mypage/ReviewModal/ReadReviewModal.stories.tsx
  src/components/mypage/ReviewModal/Write/index.tsx
  src/components/mypage/ReviewModal/Write/types.ts
  src/components/mypage/ReviewModal/WriteReviewModal.stories.tsx
  src/components/mypage/ReviewModal/index.tsx
  src/components/mypage/ReviewModal/styled.ts
  src/components/mypage/ReviewModal/types.ts
  src/hooks/useModal.ts
Labels: feat, Finish Code Review

#124 config: eslint 룰 추가
  .eslintrc.json
  src/components/home/ProductItem/index.tsx
  src/components/home/ProductList/index.tsx
  src/components/result/FilterSelect/index.tsx
  src/components/result/PriceDialog/index.tsx
  src/components/result/PriceInput/index.tsx
  src/pages/result.tsx
Labels: config, Waiting Code Review

#135 config: jotai 환경 세팅
  babel.config.js
  package.json
  src/components/common/AlertModal/index.tsx
  src/components/mypage/ReviewModal/Read/index.tsx
  src/components/mypage/ReviewModal/Write/index.tsx
  yarn.lock
Labels: config, In Progress Code Review

#134 feat: 구매자 선택 모달 버전업 Radio 적용
  src/components/mypage/SelectBuyerModal/SelectBuyerModal.stories.tsx
  src/components/mypage/SelectBuyerModal/index.tsx
  src/components/mypage/SelectBuyerModal/styled.ts
Labels: feat, In Progress Code Review

#141 config: vite 환경 제거
  package.json
  yarn.lock
Labels: config, Waiting Code Review

#143 config: husky stylelint 추가
  .husky/pre-commit
  src/components/common/CommonModal/styled.ts
  src/components/mypage/EditProfileModal/styled.ts
  src/components/mypage/ReviewModal/styled.ts
Labels: config, Waiting Code Review

#140 fix: Storybook assets 이슈 수정
  public/images/category_mangoods.svg
  public/images/pngLogo.png
  src/assets/images/category_appliance.png
  src/assets/images/category_appliance.svg
  src/assets/images/category_appliance_pc.png
  src/assets/images/category_book.png
  src/assets/images/category_book.svg
  src/assets/images/category_book_pc.png
  src/assets/images/category_car.png
  src/assets/images/category_car.svg
  src/assets/images/category_car_pc.png
  src/assets/images/category_digitaldevice.png
  src/assets/images/category_digitaldevice_pc.png
  src/assets/images/category_ditigaldevice.svg
  src/assets/images/category_ect.png
  src/assets/images/category_ect_pc.png
  src/assets/images/category_furniture.png
  src/assets/images/category_furniture.svg
  src/assets/images/category_furniture_pc.png
  src/assets/images/category_game.png
  src/assets/images/category_game.svg
  src/assets/images/category_game_pc.png
  src/assets/images/category_mangoods.png
  src/assets/images/category_mangoods.svg
  src/assets/images/category_mangoods_pc.png
  src/assets/images/category_more.png
  src/assets/images/category_more.svg
  src/assets/images/category_more_pc.png
  src/assets/images/category_petgoods.png
  src/assets/images/category_petgoods.svg
  src/assets/images/category_petgoods_pc.png
  src/assets/images/category_sports.png
  src/assets/images/category_sports.svg
  src/assets/images/category_sports_pc.png
  src/assets/images/category_toy.png
  src/assets/images/category_toy.svg
  src/assets/images/category_toy_pc.png
  src/assets/images/category_womangoods.png
  src/assets/images/category_womangoods.svg
  src/assets/images/category_womangoods_pc.png
  src/components/home/CategorySlider/index.tsx
  src/components/home/CategorySlider/styled.ts
  src/components/home/CategorySlider/types.ts
  src/constants/images.ts
  src/pages/index.tsx
  yarn.lock
Labels: feat, Waiting Code Review

#126 config : cypress 셋팅
  .eslintrc.json
  cypress.config.ts
  jest.config.ts
  next-env.d.ts
  package.json
  src/components/home/CategorySlider/index.tsx
  src/components/home/ProductList/styled.ts
  src/components/mypage/ReviewModal/styled.ts
  src/hooks/result/useCategoryFilterList.ts
  src/tests/e2e/feature/main/fixtures/apiName.json
  src/tests/e2e/feature/main/main.cy.ts
  src/tests/e2e/support/commands.ts
  src/tests/e2e/support/e2e.ts
  src/tests/e2e/tsconfig.json
  tsconfig.json
  yarn.lock
Labels: config, Finish Code Review

#144 fix: mypage 컴포넌트 순환참조 이슈 해결
  .vscode/settings.json
  src/components/mypage/ArticleList/BuyTabArticleList/index.tsx
  src/components/mypage/ArticleList/ReviewTabArticleList/index.tsx
  src/components/mypage/ArticleList/SaleTabArticleList/index.tsx
  src/components/mypage/BuyPageContent/index.tsx
  src/components/mypage/BuyPageContent/styled.ts
  src/components/mypage/ReviewPageContent/index.tsx
  src/components/mypage/ReviewPageContent/styled.ts
  src/components/mypage/SalePageContent/index.tsx
  src/components/mypage/SalePageContent/styled.ts
Labels: fix, Waiting Code Review

#146 chore: jotai 컨벤션 정의
  .gitignore
  .vscode/settings.json
  src/apis/sample/api.ts
  src/apis/sample/query.ts
  src/apis/sample/types.ts
  yarn.lock
Labels: chore
