Repository price-offer/offer-fe, pull requests merged in 2023-01, with the labels that each got.

#31 config: offer-design-system version upgrade
  package.json
  yarn.lock
Labels: config

#33 config: vitest tsconfig path alias 적용
  package.json
  vitest.config.ts
  yarn.lock
Labels: config

#36 config: offer-design-system version upgrade
  package.json
  yarn.lock
Labels: config

#38 config: offer-design-system version upgrade
  package.json
  yarn.lock
Labels: config

#42 config: Import 자동 순서 정렬 설정
  .eslintrc.json
  package.json
  src/constants/images.ts
  src/pages/_app.tsx
  src/styles/global.tsx
  src/types/index.ts
  yarn.lock
Labels: config

#47 config: offer-design-system version upgrade
  package.json
  yarn.lock
Labels: config

#51 config: offer-ui package update, 컬러 사용방식 변경
  .eslintrc.json
  package.json
  src/components/common/ConfirmModal/index.tsx
  src/styles/global.tsx
  src/styles/themes/border.ts
  src/styles/themes/colors.ts
  src/styles/themes/fonts.ts
  src/styles/themes/mediaQuery.ts
  src/styles/themes/radius.ts
  src/styles/themes/zIndex.ts
  src/types/index.ts
  src/types/theme.d.ts
  yarn.lock
Labels: config

#55 config: offer-ui package 업데이트
  package.json
  src/components/common/ConfirmModal/Modal.stories.tsx
  yarn.lock
Labels: config

#53 feat: useResponsive hook 구현 및 테스트 코드 작성
  src/hooks/index.ts
  src/hooks/useResponsive.test.ts
  src/hooks/useResponsive.ts
  src/styles/themes/mediaQuery.ts
Labels: feat

#57 release: @offer-ui/react 패키지 업데이트
  package.json
  yarn.lock
Labels: config

#60 fix: ConfirmModal 경로 이슈 해결
  src/components/common/index.ts
Labels: fix

#62 feat: 프로젝트에 필요한 공통 유틸 함수, 훅, 타입 구현
  .eslintrc.json
  src/hooks/index.ts
  src/hooks/useIsomorphicLayoutEffect.ts
  src/types/app.d.ts
  src/types/index.ts
  src/utils/common/common.test.ts
  src/utils/common/index.ts
  src/utils/format/format.test.ts
  src/utils/format/index.ts
  src/utils/index.ts
  src/utils/react/index.ts
Labels: feat

#64 config: msw 설정, mockAPI 구현 및 fixture 정의
  package.json
  public/mockServiceWorker.js
  src/apis/apis.ts
  src/apis/index.ts
  src/mocks/browser.ts
  src/mocks/fixture.ts
  src/mocks/handlers.ts
  src/mocks/index.ts
  src/mocks/server.ts
  src/pages/_app.tsx
  src/setupTest.ts
  src/tests/apis.test.ts
  src/types/index.ts
  src/types/service.ts
  tsconfig.path.json
  vitest.config.ts
  yarn.lock
Labels: config

#66 config: @offer-ui 패키지 버전 업그레이드
  package.json
  yarn.lock
Labels: config

#68 feat: Article elements 추가 타입 반영
  src/mocks/fixture.ts
  src/types/service.ts
Labels: feat

#71 feat: 프로젝트 공통 타입 정의
  src/constants/app.ts
  src/constants/index.ts
  src/types/service.ts
Labels: feat

#75 config: @offer-ui/react package update
  package.json
  yarn.lock
Labels: config

#76 config: offer-ui 패키지 업그레이드
  package.json
  yarn.lock
Labels: config

#78 fix: useResponsive hook SSR 대응
  src/hooks/useResponsive.ts
  src/styles/themes/mediaQuery.ts
Labels: fix
