Repository price-offer/offer-fe, pull requests merged in 2023-12, with the labels that each got.

#173 feat: next-cookie 적용
  .eslintrc.json
  package.json
  yarn.lock
Labels: feat, In Progress Code Review

#175 feat: Header에 로그인 정보 반영, 로그아웃
  src/apis/member/api.ts
  src/apis/member/index.ts
  src/apis/member/query.ts
  src/apis/member/types.ts
  src/components/common/Header/SideBar/index.tsx
  src/components/common/Header/SideBar/styled.ts
  src/components/common/Header/index.tsx
  src/components/common/Header/styled.ts
  src/hooks/index.ts
  src/hooks/useAuth.ts
  src/middlewares/authRedirect.ts
  src/utils/http/index.ts
Labels: feat, In Progress Code Review

#177 feat: middleware proxy 설정
  .eslintrc.json
  next.config.js
  package.json
  src/apis/auth/api.ts
  src/apis/member/api.ts
  src/apis/member/index.ts
  src/apis/member/query.ts
  src/apis/member/types.ts
  src/components/common/Header/SideBar/index.tsx
  src/components/common/Header/SideBar/styled.ts
  src/components/common/Header/index.tsx
  src/components/common/Header/styled.ts
  src/constants/env.ts
  src/hooks/index.ts
  src/hooks/useAuth.ts
  src/middleware.ts
  src/middlewares/authRedirect.ts
  src/utils/http/index.ts
  yarn.lock
Labels: feat, In Progress Code Review

#154 feat: 로그인 API 연결
  .eslintrc.json
  .vscode/settings.json
  next.config.js
  package.json
  src/apis/auth/apis.ts
  src/apis/auth/index.ts
  src/apis/auth/queries.ts
  src/apis/auth/types.ts
  src/apis/index.ts
  src/apis/member/apis.ts
  src/apis/member/index.ts
  src/apis/member/queries.ts
  src/apis/member/types.ts
  src/components/common/CommonModal/styled.ts
  src/components/common/Header/SideBar/index.tsx
  src/components/common/Header/SideBar/styled.ts
  src/components/common/Header/index.tsx
  src/components/common/Header/styled.ts
  src/constants/env.ts
  src/constants/index.ts
  src/constants/oauth.ts
  src/hooks/index.ts
  src/hooks/useAuth.ts
  src/middleware.ts
  src/middlewares/authRedirect.ts
  src/middlewares/index.ts
  src/pages/_app.tsx
  src/pages/auth/redirect/index.tsx
  src/styles/themes/colors.ts
  src/utils/format/format.test.ts
  src/utils/format/index.ts
  src/utils/http/index.ts
  tsconfig.path.json
  yarn.lock
Labels: feat, In Progress Code Review

#182 feat: 상수화된 타입, 데이터 서버측과 싱크업
  src/apis/apis.ts
  src/components/messagebox/ProductBubble/ProductBubble.stories.tsx
  src/components/messagebox/ProductBubble/index.tsx
  src/components/messagebox/ProductBubble/types.ts
  src/components/mypage/Article/BuyTabArticle/BuyTabArticle.stories.tsx
  src/components/mypage/Article/SaleTabArticle/SaleTabArticle.stories.tsx
  src/components/mypage/Article/SaleTabArticle/index.tsx
  src/components/mypage/ArticleList/BuyTabArticleList/BuyTabArticleList.stories.tsx
  src/components/mypage/ArticleList/SaleTabArticleList/SaleTabArticleList.stories.tsx
  src/components/mypage/BuyPageContent/index.tsx
  src/components/mypage/SalePageContent/index.tsx
  src/components/product/PriceOfferModal/index.tsx
  src/constants/app.ts
  src/mocks/fixture.ts
  src/pages/post/index.tsx
  src/pages/product/[productId].tsx
  src/tests/apis.test.ts
  src/types/service.ts
Labels: feat, Waiting Code Review

#183 feat: @suspensive/react 도입 및 suspense + useSuspenseQuery 형태로 변경
  package.json
  src/apis/auth/queries.ts
  src/apis/member/queries.ts
  src/components/common/Header/index.tsx
  src/components/common/Header/skeleton.tsx
  src/hooks/useAuth.ts
  src/pages/_app.tsx
  src/utils/http/index.ts
  yarn.lock
Labels: feat

#190 feat: post 페이지에서 header 로고만 보이게
  src/components/common/Header/index.tsx
  src/components/common/Header/styled.ts
  src/components/common/index.ts
  src/layouts/index.tsx
  src/pages/_app.tsx
  src/pages/post/index.tsx
Labels: feat, Waiting Code Review

#189 feat: getCategory query 등록
  src/apis/post/apis.ts
  src/apis/post/index.ts
  src/apis/post/queries.ts
  src/apis/post/types.ts
Labels: feat, Waiting Code Review

#187 chore: productDetail페 -> postDetail페로 변경
  src/components/common/Header/index.tsx
  src/components/common/Header/styled.ts
  src/components/common/index.ts
  src/components/index.ts
  src/components/post/PostField/PostField.stories.tsx
  src/components/post/PostField/index.tsx
  src/components/post/PostField/styled.ts
  src/components/post/PostField/types.ts
  src/components/post/PriceOfferCard/PriceOffer.stories.tsx
  src/components/post/PriceOfferCard/index.tsx
  src/components/post/PriceOfferCard/styled.ts
  src/components/post/PriceOfferCard/types.ts
  src/components/post/PriceOfferModal/PriceOfferModal.stories.tsx
  src/components/post/PriceOfferModal/index.tsx
  src/components/post/PriceOfferModal/styled.ts
  src/components/post/PriceOfferModal/types.ts
  src/components/post/UserProfile/UserProfile.stories.tsx
  src/components/post/UserProfile/index.tsx
  src/components/post/UserProfile/styled.ts
  src/components/post/UserProfile/types.ts
  src/components/post/index.ts
  src/components/product/ProductField/ProductField.stories.tsx
  src/components/product/ProductField/types.ts
  src/components/product/index.ts
  src/layouts/index.tsx
  src/pages/_app.tsx
  src/pages/post/[postId]/index.tsx
  src/pages/post/index.tsx
Labels: chore, Waiting Code Review

#191 fix: 서비스 전체 JS 깨짐 현상 디버깅
  src/layouts/index.tsx
  src/pages/_app.tsx
Labels: fix

#193 config: @offer-ui/react 패키지 버전 업그레이드
  package.json
  src/components/home/ProductItem/index.tsx
  src/hooks/index.ts
  src/hooks/useIsomorphicLayoutEffect.ts
  yarn.lock
Labels: config

#201 feat: 변경된 scheme를 기반 api dto 정의
  src/apis/auth/types.ts
  src/apis/image/index.ts
  src/apis/image/types.ts
  src/apis/index.ts
  src/apis/like/index.ts
  src/apis/like/types.ts
  src/apis/member/apis.ts
  src/apis/member/types.ts
  src/apis/message/index.ts
  src/apis/message/types.ts
  src/apis/offer/index.ts
  src/apis/offer/types.ts
  src/apis/post/types.ts
  src/apis/review/index.ts
  src/apis/review/types.ts
Labels: feat

#198 config: msw 관련 환경 및 mock api 제거
  package.json
  src/apis/apis.ts
  src/apis/sample/api.ts
  src/apis/sample/query.ts
  src/apis/sample/types.ts
  src/constants/env.ts
  src/mocks/browser.ts
  src/mocks/fixture.ts
  src/mocks/handlers.ts
  src/mocks/index.ts
  src/mocks/server.ts
  src/pages/_app.tsx
  src/setupTest.ts
  src/tests/apis.test.ts
  yarn.lock
Labels: config

#200 feat: find 유틸 함수 구현
  src/apis/auth/types.ts
  src/apis/image/index.ts
  src/apis/image/types.ts
  src/apis/index.ts
  src/apis/like/index.ts
  src/apis/like/types.ts
  src/apis/member/apis.ts
  src/apis/member/types.ts
  src/apis/message/index.ts
  src/apis/message/types.ts
  src/apis/offer/index.ts
  src/apis/offer/types.ts
  src/apis/post/types.ts
  src/apis/review/index.ts
  src/apis/review/types.ts
  src/utils/common/common.test.ts
  src/utils/common/index.ts
Labels: feat

#199 feat: 변경된 BE 스키마 반영한 타입 선언 및 상수화
  src/apis/auth/types.ts
  src/apis/image/index.ts
  src/apis/image/types.ts
  src/apis/index.ts
  src/apis/like/index.ts
  src/apis/like/types.ts
  src/apis/member/apis.ts
  src/apis/member/types.ts
  src/apis/message/index.ts
  src/apis/message/types.ts
  src/apis/offer/index.ts
  src/apis/offer/types.ts
  src/apis/post/types.ts
  src/apis/review/index.ts
  src/apis/review/types.ts
  src/components/messagebox/ProductBubble/index.tsx
  src/constants/app.ts
  src/types/index.ts
  src/types/scheme.ts
  src/types/service.ts
  src/utils/common/common.test.ts
  src/utils/common/index.ts
Labels: feat

#197 feat: 글로벌 유틸리티 타입 구현
  .vscode/settings.json
  package.json
  src/@types/global.d.ts
  src/apis/apis.ts
  src/apis/auth/types.ts
  src/apis/image/index.ts
  src/apis/image/types.ts
  src/apis/index.ts
  src/apis/like/index.ts
  src/apis/like/types.ts
  src/apis/member/apis.ts
  src/apis/member/types.ts
  src/apis/message/index.ts
  src/apis/message/types.ts
  src/apis/offer/index.ts
  src/apis/offer/types.ts
  src/apis/post/types.ts
  src/apis/review/index.ts
  src/apis/review/types.ts
  src/apis/sample/api.ts
  src/apis/sample/query.ts
  src/apis/sample/types.ts
  src/components/messagebox/ProductBubble/index.tsx
  src/constants/app.ts
  src/constants/env.ts
  src/mocks/browser.ts
  src/mocks/fixture.ts
  src/mocks/handlers.ts
  src/mocks/index.ts
  src/mocks/server.ts
  src/pages/_app.tsx
  src/setupTest.ts
  src/tests/apis.test.ts
  src/types/app.ts
  src/types/index.ts
  src/types/scheme.ts
  src/types/service.ts
  src/utils/common/common.test.ts
  src/utils/common/index.ts
  tsconfig.json
  yarn.lock
Labels: feat

#204 refactor: useSuspenseQuery를 useQuery로 변경
  src/apis/member/data.ts
  src/apis/member/queries.ts
  src/components/common/Header/index.tsx
  src/components/common/Header/skeleton.tsx
  src/layouts/index.tsx
Labels: feat, fix

#209 config: @offer-ui/react version upgrade
  package.json
  yarn.lock
Labels: config

#168 Feat/#155 메인 페이지 카테고리 목록 + 상품 api 연동
  package.json
  src/apis/post/apis.ts
  src/apis/post/queries.ts
  src/assets/images/category_books.svg
  src/assets/images/category_digital.svg
  src/assets/images/category_menfashion.svg
  src/assets/images/category_other.svg
  src/assets/images/category_pet.svg
  src/assets/images/category_womanfashion.svg
  src/components/home/CategorySlider/index.tsx
  src/components/home/CategorySlider/styled.ts
  src/components/home/ProductItem/index.tsx
  src/components/home/ProductItem/types.ts
  src/components/home/ProductList/index.tsx
  src/components/home/ProductList/styled.ts
  src/components/home/ProductList/types.ts
  src/constants/images.ts
  src/mocks/fixture.ts
  src/pages/index.tsx
  src/pages/result/index.tsx
  src/utils/format/index.ts
  yarn.lock
Labels: feat, Waiting Code Review

#213 fix: dto 변경에 따른 이슈 대응
  src/apis/post/apis.ts
  src/apis/post/queries.ts
  src/apis/post/types.ts
  src/components/common/CommonModal/types.ts
  src/components/home/ProductItem/index.tsx
  src/components/home/ProductItem/types.ts
  src/components/home/ProductList/types.ts
  src/components/messagebox/MessageBoxPlaceholder/types.ts
  src/components/post/PostField/types.ts
  src/components/post/PriceOfferModal/index.tsx
  src/mocks/fixture.ts
  src/pages/index.tsx
  src/pages/post/index.tsx
  src/pages/shop/view/buy/index.tsx
  src/pages/shop/view/review/index.tsx
  src/pages/shop/view/sale/index.tsx
Labels: feat, Waiting Code Review

#214 fix: 외부 이미지 관련 에러 디버깅
  next.config.js
Labels: fix

#217 config: ods version upgrade
  package.json
  yarn.lock
Labels: config

#179 feat: 상품 판매글 작성 구현
  src/apis/image/apis.ts
  src/apis/image/index.ts
  src/apis/image/queries.ts
  src/apis/image/types.ts
  src/apis/post/apis.ts
  src/apis/post/queries.ts
  src/apis/post/types.ts
  src/pages/post/index.tsx
  src/types/scheme.ts
  src/utils/format/index.ts
Labels: feat, In Progress Code Review

#192 feat: 상품 상세 페이지 api 연결
  src/apis/offer/apis.ts
  src/apis/offer/index.ts
  src/apis/offer/queries.ts
  src/apis/offer/types.ts
  src/apis/post/apis.ts
  src/apis/post/index.ts
  src/apis/post/queries.ts
  src/components/post/PostField/PostField.stories.tsx
  src/components/post/PostField/index.tsx
  src/components/post/PostField/types.ts
  src/components/post/PostFieldList/PostFieldList.stories.tsx
  src/components/post/PostFieldList/index.tsx
  src/components/post/PostFieldList/styled.ts
  src/components/post/PostFieldList/types.ts
  src/components/post/PriceOfferCard/PriceOffer.stories.tsx
  src/components/post/PriceOfferCard/index.tsx
  src/components/post/PriceOfferCard/styled.ts
  src/components/post/PriceOfferCard/types.ts
  src/components/post/UserProfile/UserProfile.stories.tsx
  src/components/post/UserProfile/index.tsx
  src/components/post/UserProfile/types.ts
  src/components/post/index.ts
  src/pages/post/[postId]/index.tsx
  src/types/scheme.ts
Labels: feat, In Progress Code Review

#203 feat: 상품 단건 페이지 구매자인 경우 api 연결
  src/apis/like/apis.ts
  src/apis/like/index.ts
  src/apis/like/queries.ts
  src/apis/offer/apis.ts
  src/apis/offer/queries.ts
  src/apis/offer/types.ts
  src/components/common/AlertModal/AlertModal.stories.tsx
  src/components/common/Header/index.tsx
  src/components/post/PriceOfferCard/PriceOffer.stories.tsx
  src/components/post/PriceOfferCard/index.tsx
  src/components/post/PriceOfferCard/styled.ts
  src/components/post/PriceOfferCard/types.ts
  src/components/post/PriceOfferModal/index.tsx
  src/components/post/PriceOfferModal/types.ts
  src/components/post/UserProfile/UserProfile.stories.tsx
  src/components/post/UserProfile/types.ts
  src/components/shop/ReviewModal/ReadReviewModal.stories.tsx
  src/components/shop/ReviewModal/WriteReviewModal.stories.tsx
  src/hooks/useModal.ts
  src/pages/messagebox/index.tsx
  src/pages/post/[postId]/index.tsx
  src/types/scheme.ts
Labels: feat, In Progress Code Review

#218 refactor: 변경된 scheme 적용
  src/@types/global.d.ts
  src/apis/like/types.ts
  src/apis/review/types.ts
  src/components/post/PostFieldList/index.tsx
  src/components/post/PostFieldList/types.ts
  src/components/post/PriceOfferCard/index.tsx
  src/components/post/UserProfile/UserProfile.stories.tsx
  src/components/post/UserProfile/index.tsx
  src/components/post/UserProfile/types.ts
  src/components/shop/Post/BuyTabPost/BuyTabPost.stories.tsx
  src/components/shop/Post/BuyTabPost/likeTabPanel/index.tsx
  src/components/shop/Post/BuyTabPost/offerTabPanel/index.tsx
  src/components/shop/Post/SaleTabPost/SaleTabPost.stories.tsx
  src/components/shop/Post/SaleTabPost/index.tsx
  src/components/shop/PostList/BuyTabPostList/BuyTabPostList.stories.tsx
  src/pages/messagebox/index.tsx
  src/pages/post/[postId]/index.tsx
  src/pages/shop/view/buy/index.tsx
  src/pages/shop/view/review/index.tsx
  src/types/scheme.ts
  src/utils/common/index.ts
Labels: feat, fix
