Repository price-offer/offer-fe, pull requests merged in 2024-01, with the labels that each got.

#222 config: @offer-ui/react version upgrade v0.2.7
  package.json
  yarn.lock
Labels: config

#224 config: ods version upgrade
  package.json
  yarn.lock
Labels: config, Waiting Code Review

#220 feat: 변경된 api dto 반영
  src/apis/message/types.ts
  src/components/shop/Post/ReviewTabPost/ReviewTabPost.stories.tsx
  src/components/shop/Post/ReviewTabPost/index.tsx
  src/components/shop/Post/ReviewTabPost/types.ts
  src/components/shop/PostList/ReviewTabPostList/ReviewTabPostList.stories.tsx
  src/components/shop/PostList/ReviewTabPostList/types.ts
  src/constants/app.ts
  src/types/scheme.ts
Labels: feat

#228 version upgrade offer-ui package
  package.json
  yarn.lock
Labels: chore

#230 config: ods version up
  package.json
  src/pages/post/[postId]/index.tsx
  yarn.lock
Labels: config

#233 config: ods version up
  package.json
  src/components/common/Header/SearchArea/index.tsx
  src/components/common/Header/SearchArea/styled.ts
  src/components/common/Header/index.tsx
  src/components/common/Header/styled.ts
  src/components/messagebox/ChattingRoom/index.tsx
  src/pages/post/index.tsx
  yarn.lock
Labels: config, Waiting Code Review

#226 feat: 구매자가 제안된 가격에 쪽지보내는 api 붙이기
  src/apis/message/apis.ts
  src/apis/message/index.ts
  src/apis/message/queries.ts
  src/components/post/PriceOfferCard/index.tsx
  src/components/post/PriceOfferCard/styled.ts
  src/pages/post/[postId]/index.tsx
  src/pages/post/index.tsx
Labels: feat, Finish Code Review

#231 feat: 포스팅 상세페 이미지 모달 붙이기 #206
  src/apis/post/queries.ts
  src/pages/post/[postId]/index.tsx
Labels: feat, Finish Code Review

#196 feat: 쪽지함 api 연결
  src/apis/message/apis.ts
  src/apis/message/queries.ts
  src/apis/message/types.ts
  src/components/common/Header/SideBar/index.tsx
  src/components/common/Header/SideBar/styled.ts
  src/components/messagebox/Chatting/Chatting.stories.tsx
  src/components/messagebox/Chatting/index.tsx
  src/components/messagebox/Chatting/types.ts
  src/components/messagebox/ChattingRoom/ChattingRoom.stories.tsx
  src/components/messagebox/ChattingRoom/index.tsx
  src/components/messagebox/ChattingRoom/styled.ts
  src/components/messagebox/ChattingRoom/types.ts
  src/components/messagebox/MessagePreview/MessagePreview.stories.tsx
  src/components/messagebox/MessagePreview/index.tsx
  src/components/messagebox/MessagePreview/types.ts
  src/constants/app.ts
  src/pages/messagebox/index.tsx
  src/types/scheme.ts
  src/types/service.ts
  src/utils/format/index.ts
Labels: feat, Finish Code Review

#225 feat: 게시글 삭제, 수정 기능 구현
  src/apis/post/apis.ts
  src/apis/post/queries.ts
  src/apis/post/types.ts
  src/components/common/Dialog/index.tsx
  src/components/post/UserProfile/index.tsx
  src/components/post/UserProfile/types.ts
  src/pages/post/[postId]/index.tsx
  src/pages/post/index.tsx
Labels: feat, In Progress Code Review

#174 feat:결과페이지 api 및 스타일 작업
  src/apis/post/apis.ts
  src/apis/post/types.ts
  src/components/home/CategorySlider/index.tsx
  src/components/home/CategorySlider/styled.ts
  src/components/result/CategoryHeader/index.tsx
  src/components/result/CategoryHeader/types.ts
  src/components/result/FilterSelect/index.tsx
  src/components/result/FilterSelect/styled.ts
  src/components/result/FilterSelect/types.ts
  src/components/result/PriceDialog/index.tsx
  src/components/result/PriceDialog/styled.ts
  src/components/result/PriceDialog/types.ts
  src/components/result/ProductFilterSelect/index.tsx
  src/components/result/index.ts
  src/hooks/index.ts
  src/hooks/result/useCategoryFilterList.ts
  src/hooks/result/useSelectBoxFilter.ts
  src/pages/result/index.tsx
  src/tests/e2e/feature/main/main.cy.ts
  src/types/service.ts
  src/utils/service/result/index.ts
Labels: feat, In Progress Code Review

#235 fix: 빌드 시, pages default export 문제 해결
  babel.config.js
  src/components/shop/EditProfileModal/index.tsx
  src/components/shop/buy/index.ts
  src/components/shop/buy/panel/index.tsx
  src/components/shop/buy/panel/styled.ts
  src/components/shop/buy/panel/view/like.tsx
  src/components/shop/buy/panel/view/offer.tsx
  src/components/shop/index.ts
  src/components/shop/layout/index.tsx
  src/components/shop/layout/styled.tsx
  src/components/shop/pageTabs.ts
  src/components/shop/review/index.ts
  src/components/shop/review/panel/index.tsx
  src/components/shop/review/panel/styled.ts
  src/components/shop/sale/index.ts
  src/components/shop/sale/panel/index.tsx
  src/components/shop/sale/panel/styled.ts
  src/pages/shop/[id].tsx
  src/pages/shop/index.tsx
Labels: fix

#236 feat: post 페이지 관련 routing 처리
  src/apis/post/queries.ts
  src/constants/message.ts
  src/hooks/index.ts
  src/hooks/usePreventLeavePage.ts
  src/pages/post/[postId]/index.tsx
  src/pages/post/index.tsx
Labels: feat, Waiting Code Review

#238 feat: 메인, 결과물 페이지 기능 추가 구현
  src/apis/post/queries.ts
  src/components/home/CategorySlider/index.tsx
  src/components/home/ProductItem/index.tsx
  src/components/home/ProductItem/styled.ts
  src/components/home/ProductItem/types.ts
  src/components/home/ProductList/index.tsx
  src/components/home/ProductList/styled.ts
  src/components/result/CategoryHeader/index.tsx
  src/components/result/CategoryHeader/types.ts
  src/components/result/CategorySlideFilter/index.tsx
  src/components/result/CategorySlideFilter/types.ts
  src/components/result/FilterSelect/index.tsx
  src/components/result/FilterSelect/types.ts
  src/components/result/PriceDialog/index.tsx
  src/components/result/PriceDialog/types.ts
  src/components/result/SearchOptions/index.tsx
  src/components/result/SearchOptions/styled.ts
  src/components/result/SearchOptions/types.ts
  src/components/result/index.ts
  src/hooks/index.ts
  src/hooks/result/useCategoryFilterList.ts
  src/hooks/result/useSelectBoxFilter.ts
  src/pages/result/index.tsx
  src/styles/themes/zIndex.ts
  src/utils/service/result/index.ts
Labels: feat

#241 feat: 검색 기능 구현
  .eslintrc.json
  src/apis/post/types.ts
  src/atoms/index.ts
  src/atoms/search.ts
  src/components/common/Header/SearchArea/index.tsx
  src/components/common/Header/SearchArea/types.ts
  src/components/common/Header/index.tsx
  src/components/home/ProductItem/styled.ts
  src/components/home/ProductList/styled.ts
  src/components/post/PriceOfferCard/index.tsx
  src/components/result/PriceDialog/types.ts
  src/components/result/SearchOptions/types.ts
  src/constants/index.ts
  src/constants/oauth.ts
  src/pages/messagebox/index.tsx
  src/pages/post/[postId]/index.tsx
  src/pages/result/index.tsx
  src/utils/format/format.test.ts
  src/utils/format/index.ts
  tsconfig.path.json
Labels: feat, Waiting Code Review

#242 feat: main, result 페이지 placeholder 추가
  src/components/home/ProductList/index.tsx
  src/components/home/ProductList/styled.ts
  src/pages/index.tsx
  src/pages/result/index.tsx
Labels: feat, Waiting Code Review

#247 config: ods version up
  package.json
  yarn.lock
Labels: feat

#248 fix: Input.Edit 가격이 아닌 경우도 가능하도록
  package.json
  yarn.lock
Labels: fix

#250 fix: 로그인 안 했을 때, [판매하기]를 누르면 반응이 없어서 오류상황처럼 느껴짐
  src/components/common/Header/index.tsx
  src/components/common/Header/styled.ts
  src/components/common/LoginModal/LoginModal.stories.tsx
  src/components/common/LoginModal/index.tsx
  src/components/common/LoginModal/styled.ts
  src/components/common/LoginModal/types.ts
  src/components/common/index.ts
  src/components/home/HomeBanner/index.tsx
  src/constants/index.ts
  src/constants/url.ts
Labels: fix, Waiting Code Review

#257 fix: 구매자일 때, 선택 라디오 버튼이 뜸
  src/components/post/PriceOfferCard/index.tsx
  src/components/post/PriceOfferCard/styled.ts
Labels: fix, Waiting Code Review

#260 fix: 상품정보 수정 시, 신규 상품으로 등록됨
  src/pages/post/index.tsx
Labels: fix, Waiting Code Review

#262 design: 2차 UI 수정
  src/components/home/ProductItem/styled.ts
  src/components/home/ProductList/styled.ts
  src/pages/messagebox/index.tsx
Labels: design, Waiting Code Review

#265 config: ods package upgrade
  package.json
  yarn.lock
Labels: config
